"""Every task `bird/envs/upstream_assistax.py` registers, held to the SAME contract.

`tests/test_upstream_assistax.py` is written against one id (scratchitch, the
first adapted). For feeding, teethbrushing and armmanipulation the per-task hook
`_derived_xp` is the only thing a subclass writes, so the contract the scratchitch tests pin -- the host
row and the device row are one function, the row is as wide as the spec says,
the CPU check evaluates on a banked row, the renderer draws -- is exactly what
a new task can get wrong. These tests run that contract over EVERY id in
`_CLASSES`, so adding a fifth task adds its parametrization for free and
forgetting a spec or a slot width fails by name.

The offline half needs no simulator; the `jax` half constructs upstream's env
and skips in the default CI job like every other `-m jax` test (it needs the jax venv:
`scripts/setup_jax.sh`, then `uv run --no-sync --python .venv-jax/bin/python3
python3 -m pytest tests/test_upstream_assistax_tasks.py -m jax`).
"""
from __future__ import annotations

import numpy as np
import pytest

from bird import config as bird_config
from bird import registry, tasks
from bird.envs import upstream_assistax as up

IDS = sorted(f"upstream_assistax_{t}" for t in up._CLASSES)


def _factory(env_id):
    registry.load_all()
    return registry.get("env", env_id)


# -- offline: the catalogue half ----------------------------------------------

def test_the_registered_ids_are_the_class_table_and_nothing_else():
    registry.load_all()
    registered = sorted(n for n in registry.names("env") if n.startswith("upstream_assistax_"))
    assert registered == IDS
    # bedbathing is the one held out (validator-blocked; TERMINATES); a fifth
    # registration must come with its own class, not a stub.
    assert set(up.UNADAPTED) == set(up.UPSTREAM_TASKS) - set(up._CLASSES)


@pytest.mark.parametrize("env_id", IDS)
def test_every_registered_task_has_a_generated_spec_naming_it(env_id):
    spec = tasks.index()[env_id]
    assert spec.bird_env_id == env_id
    text = spec.path.read_text()
    assert "GENERATED by scripts/derive_jax_spec.py" in text.splitlines()[0]


@pytest.mark.parametrize("env_id", IDS)
def test_the_spec_gate_is_a_superset_of_every_tasks_adapter_tuple(env_id):
    """`--union-adapter-gate <id>` at derivation is what puts the adapter's
    tuple into the spec; a spec derived without it silently drops the tier's
    own bans (measured: 109 symbols on scratchitch)."""
    spec_gate = set(bird_config.forbidden_symbols_of(tasks.index()[env_id]))
    adapter_gate = set(_factory(env_id).consumer_forbidden_symbols)
    missing = adapter_gate - spec_gate
    assert not missing, (
        f"{env_id}: {len(missing)} adapter-gate symbols missing from the spec's gate "
        f"(re-derive with --union-adapter-gate {env_id}): {sorted(missing)[:8]}")


@pytest.mark.parametrize("env_id", IDS)
def test_each_subclass_names_its_own_tool_site_and_obs_arity(env_id):
    cls = _factory(env_id).adapter_cls
    assert cls.task == env_id.removeprefix("upstream_assistax_")
    # The base class defaults are scratchitch's; a subclass that inherits them
    # on another task reads a site index that does not exist in its model.
    if cls.task != "scratchitch":
        assert "tool_site_attr" in cls.__dict__, f"{cls.__name__} inherits scratchitch's tool site"
        assert "robo_obs_takes_info" in cls.__dict__, f"{cls.__name__} inherits scratchitch's obs arity"
    assert "_derived_xp" in cls.__dict__, f"{cls.__name__} does not build its own derived"


@pytest.mark.parametrize("env_id", IDS)
def test_the_checks_inputs_are_all_banked_tail_columns(env_id):
    """`task_metric` rebuilds a `_Derived`-alike from ONE STORED ROW (`_row_derived`)
    and hands it to the CPU module's check. Every `D.<name>` the check reads must
    therefore be a tail column (or an alias of one) -- and the tail's names are
    not the check's names on two tasks (`dist_tool_mouth` vs `D.dist`,
    `brush_tangential_speed` vs `D.tangential_speed`). Without this check the
    failure shape is every offline test green and the first `task_metric` call
    an AttributeError (measured on teethbrushing). This runs without a simulator: a zeros
    row of the tail's width through the real `_row_derived`, then the check's
    source read for the attributes it touches."""
    import inspect
    import re
    import types
    from bird.envs import assistax as cpu
    task = env_id.removeprefix("upstream_assistax_")
    tail = getattr(cpu, f"_TAIL_{task.upper()}")
    fake = types.SimpleNamespace(task=task, _tail=tail)
    row = np.zeros(len(tail) + 10 + up._N_SLOTS.get(task, 0))
    d = up.UpstreamAssistax._row_derived(fake, row)
    check = cpu._TASKS[task]["check"]
    reads = set(re.findall(r"\bD\.([A-Za-z_]\w*)", inspect.getsource(check)))
    reads -= {"xp"}
    missing = sorted(a for a in reads if not hasattr(d, a))
    assert not missing, f"{env_id}: the check reads {missing}, which _row_derived does not bank"
    assert reads, f"{env_id}: the check reads nothing from D -- the regex missed it"


# -- with the simulator: the row contract ----------------------------------------

@pytest.fixture(scope="module")
def envs():
    pytest.importorskip("assistax")
    return {}


def _env(envs, env_id):
    if env_id not in envs:
        envs[env_id] = _factory(env_id).adapter_cls(None)
    return envs[env_id]


@pytest.mark.jax
@pytest.mark.parametrize("env_id", IDS)
def test_the_row_is_as_wide_as_the_spec_and_the_tail_says(envs, env_id):
    env = _env(envs, env_id)
    spec = tasks.index()[env_id]
    nq, nv = int(env._env.sys.q_size()), int(env._env.sys.qd_size())
    width = nq + nv + up._N_SLOTS.get(env.task, 0) + len(env._tail)
    assert env.obs_dim == width
    assert int(spec.spaces["obs_dim"]) == width if hasattr(spec, "spaces") else True
    row = env.reset(np.random.default_rng(0))
    assert np.asarray(row).shape == (width,)
    assert env.action_dim == 7


@pytest.mark.jax
@pytest.mark.parametrize("env_id", IDS)
def test_the_jax_row_matches_the_host_row_column_by_column(envs, env_id):
    """Per column on a STEPPED sequence (differenced columns are zero at reset)."""
    env = _env(envs, env_id)
    names = ([f"qpos[{i}]" for i in range(int(env._env.sys.q_size()))]
             + [f"qvel[{i}]" for i in range(int(env._env.sys.qd_size()))]
             + [f"slot[{i}]" for i in range(up._N_SLOTS.get(env.task, 0))]
             + [t[0] for t in env._tail])
    rng = np.random.default_rng(0)
    host = env.reset(rng)
    rows = [(np.asarray(host), np.asarray(env.row_jax(env._last_state)), 0)]
    for k in range(1, 4):
        prev_state = env._last_state
        host, _done, _info = env.step(host, np.clip(rng.normal(0, 0.3, 7), -1, 1))
        rows.append((np.asarray(host), np.asarray(env.row_jax(env._last_state, prev_state)), k))
    assert len(names) == env.obs_dim
    bad = [f"step {k} col {i} ({names[i]}): host={h[i]!r} jax={j[i]!r}"
           for h, j, k in rows for i in range(env.obs_dim)
           if not np.isclose(h[i], j[i], rtol=1e-6, atol=1e-7)]
    assert not bad, "host and device rows disagree:\n  " + "\n  ".join(bad[:12])
    # A tail column that is identically zero across a stepped sequence on
    # every step is the zeroed-field shape; name it.
    tail0 = env.obs_dim - len(env._tail)
    const = [names[tail0 + i] for i in range(len(env._tail))
             if all(abs(h[tail0 + i]) < 1e-12 for h, _j, _k in rows)]
    allowed_zero = {"tip_force_mag", "tool_fx", "tool_fy", "tool_fz"}  # no contact yet is real
    assert set(const) <= allowed_zero, f"tail columns identically zero over 4 steps: {const}"


@pytest.mark.jax
@pytest.mark.parametrize("env_id", IDS)
def test_the_check_evaluates_on_banked_rows_and_the_reference_is_upstreams(envs, env_id):
    env = _env(envs, env_id)
    rng = np.random.default_rng(1)
    s = env.reset(rng)
    traj = [s]
    for _ in range(3):
        a = np.clip(rng.normal(0, 0.3, 7), -1, 1)
        s, done, info = env.step(s, a)
        traj.append(s)
        assert done is False
        assert "success" in info
        r = env.reference_reward(s, a)
        assert np.isfinite(r)
    m = env.task_metric(np.stack(traj))
    assert 0.0 <= m <= 1.0
    assert isinstance(env.success(np.stack(traj)), bool)


@pytest.mark.jax
@pytest.mark.parametrize("env_id", IDS)
def test_row_jax_traces_under_jit(envs, env_id):
    import jax
    env = _env(envs, env_id)
    env.reset(np.random.default_rng(0))
    st = env._last_state
    f = jax.jit(lambda s: env.row_jax(s))
    out = np.asarray(f(st))
    assert out.shape == (env.obs_dim,)
    assert np.all(np.isfinite(out))


@pytest.mark.jax
@pytest.mark.parametrize("env_id", IDS)
def test_render_returns_a_frame(envs, env_id):
    env = _env(envs, env_id)
    s = env.reset(np.random.default_rng(0))
    try:
        frame = env.render(s)
    except Exception as exc:  # noqa: BLE001 -- no GL on this machine is a skip, not a defect
        pytest.skip(f"renderer unavailable here: {type(exc).__name__}: {exc}")
    assert frame.shape == (env.render_height, env.render_width, 3)
